# Generated by Django 4.2.1 on 2023-06-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabalho1app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="nota",
            field=models.IntegerField(verbose_name="Nota"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="periodo_ingresso",
            field=models.CharField(max_length=100, verbose_name="Período de Ingresso"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="situacao",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                verbose_name="Situação",
            ),
        ),
    ]
